# VMware Fusion NAT: сеть 172.16.114.0/24, DHCP начинается с .128.
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses:
        - 172.16.114.20/24
      routes:
        - to: default
          via: 172.16.114.2
      nameservers:
        addresses:
          - 172.16.114.2
    ens256:
      dhcp4: false
      link-local: []
      optional: true
